"underscore":
  url: "https://github.com/documentcloud/underscore/raw/{version}/underscore.js"
  description: "javascript's utility belt"
  compressed_url: "http://cdnjs.cloudflare.com/ajax/libs/underscore.js/{version}/underscore-min.js"
  version: "1.2.0"

"raphael":
  url: "https://github.com/DmitryBaranovskiy/raphael/raw/v{version}/raphael.js"
  description: "raphael vector library"
  compressed: "raphael-min.js"
  version: "1.4.7"

"g.raphael":
  url: "https://github.com/DmitryBaranovskiy/g.raphael/raw/v{version}/g.raphael.js"
  description: "charting for raphael"
  compressed: "g.raphael-min.js"
  version: "0.4.1"
  dependencies:
    "raphael": "1.4.7"

"g.bar":
  url: "https://github.com/DmitryBaranovskiy/g.raphael/raw/v{version}/g.bar.js"
  description: "bar charting for raphael"
  compressed: "g.bar-min.js"
  version: "0.4.1"
  dependencies:
    "g.raphael": "0.4.1"

"g.dot":
  url: "https://github.com/DmitryBaranovskiy/g.raphael/raw/v{version}/g.dot.js"
  description: "dot charting for raphael"
  compressed: "g.dot-min.js"
  version: "0.4.1"
  dependencies:
    "g.raphael": "0.4.1"

"g.line":
  url: "https://github.com/DmitryBaranovskiy/g.raphael/raw/v{version}/g.line.js"
  description: "line charting for raphael"
  compressed: "g.line-min.js"
  version: "0.4.1"
  dependencies:
    "g.raphael": "0.4.1"

"g.pie":
  url: "https://github.com/DmitryBaranovskiy/g.raphael/raw/v{version}/g.pie.js"
  description: "pie charting for raphael"
  compressed: "g.pie-min.js"
  version: "0.4.1"
  dependencies:
    "g.raphael": "0.4.1"

"jquery":
  url: "http://code.jquery.com/jquery-{version}.js"
  description: "jquery core framework"
  compressed: "jquery-{version}.min.js"
  file_name: "jquery.js"
  version: "1.6.2"

"jquery-mobile":
  url: "http://code.jquery.com/mobile/{version}/jquery.mobile-{version}.js"
  description: "touch-optimized web framework for smartphones & tablets"
  file_name: "jquery.mobile.js"
  version: "1.0a4"
  dependencies:
    "jquery": "1.5.1"

"processing.js":
  url: "http://processingjs.org/content/download/processing-js-{version}/processing-{version}.js"
  description: "a port of the Processing visualization language"
  file_name: "processing.js"
  version: "1.1.0"

"d3":
  url: "https://github.com/mbostock/d3/raw/v{version}/d3.js"
  description: "A JavaScript visualization library for HTML and SVG."
  file_name: "d3.js"
  version: "1.17.0"

"d3.behavior":
  url: "https://github.com/mbostock/d3/raw/v{version}/d3.behavior.js"
  description: "Event module for d3. A JavaScript visualization library for HTML and SVG."
  version: "1.11.0"
  dependencies:
    "d3": "1.17.0"

"d3.chart":
  url: "https://github.com/mbostock/d3/raw/v{version}/d3.chart.js"
  description: "Chart module for d3. A JavaScript visualization library for HTML and SVG."
  version: "1.11.0"
  dependencies:
    "d3": "1.17.0"

"d3.csv":
  url: "https://github.com/mbostock/d3/raw/v{version}/d3.csv.js"
  description: "CSV parser module for d3. A JavaScript visualization library for HTML and SVG."
  version: "1.11.0"
  dependencies:
    "d3": "1.17.0"

"d3.geo":
  url: "https://github.com/mbostock/d3/raw/v{version}/d3.geo.js"
  description: "Geo module for d3. A JavaScript visualization library for HTML and SVG."
  version: "1.11.0"
  dependencies:
    "d3": "1.17.0"

"d3.geom":
  url: "https://github.com/mbostock/d3/raw/v{version}/d3.geom.js"
  description: "Geometry module for d3. A JavaScript visualization library for HTML and SVG."
  version: "1.11.0"
  dependencies:
    "d3": "1.17.0"

"d3.layout":
  url: "https://github.com/mbostock/d3/raw/v{version}/d3.layout.js"
  description: "Layout module for d3. A JavaScript visualization library for HTML and SVG."
  version: "1.11.0"
  dependencies:
    "d3": "1.17.0"

"d3.time":
  url: "https://github.com/mbostock/d3/raw/v{version}/d3.time.js"
  description: "Time module for d3. A JavaScript visualization library for HTML and SVG."
  version: "1.11.0"
  dependencies:
    "d3": "1.17.0"

"date.js":
  url: "http://datejs.googlecode.com/files/date.js"
  description: "Datejs is an open source JavaScript Date library for parsing, formatting and processing."
  version: "1.0 Alpha-1"

"backbone":
  url: "https://github.com/documentcloud/backbone/raw/{version}/backbone.js"
  compressed_url: "http://cdnjs.cloudflare.com/ajax/libs/backbone.js/{version}/backbone-min.js"
  description: "Backbone supplies structure to Javascript Apps by providing models, views, collections, and events"
  version: "0.5.3"

"zepto":
  url: "https://github.com/madrobby/zepto/raw/v{version}/src/zepto.js"
  description: "zepto.js is a minimalist inlinable framework for mobile WebKit browsers, with a jQuery-like chaining syntax"
  version: "0.5"

"iscroll":
  url: "https://github.com/cubiq/iscroll/raw/master/src/iscroll.js"
  description: "Hardware accelerated scroll for mobile webkit"
  version: "4.0"

"iscroll-lite":
  url: "https://github.com/cubiq/iscroll/raw/master/src/iscroll-lite.js"
  description: "Hardware accelerated scroll for mobile webkit"
  version: "4.0"

"modernizr":
  url: "http://www.modernizr.com/downloads/modernizr-{version}.js"
  file_name: "modernizr.js"
  description: "Feature detection to test browsers against upcoming features"
  version: "2.0.6"

"mustache.js":
  url: "https://raw.github.com/janl/mustache.js/{version}/mustache.js"
  description: "Minimal templating with {{mustaches}} in JavaScript"
  version: "0.3.0"

"jasmine-jquery.js":
  url: "https://github.com/downloads/velesin/jasmine-jquery/jasmine-jquery-{version}.js"
  description: "jQuery matchers and fixture loader for Jasmine framework"
  version: "1.3.1"
  file_name: "jasmine-jquery.js"

"jquery.cycle.js":
  url: "https://raw.github.com/malsup/cycle/master/jquery.cycle.all.js"
  description: "Javascript jQuery plugin - Slideshow goodness"
  version: "2.9995"
  file_name: "jquery.cycle.js"
  dependencies:
    "jquery": "1.3.2"

"bootstrap-sass.css":
  url: "https://raw.github.com/jlong/sass-twitter-bootstrap/master/bootstrap-{version}.css"
  description: "Twitter Bootstrap framework converted to SASS"
  version: "1.1.1"
  file_name: "bootstrap-sass.css"

"qunit.js":
  url: "http://code.jquery.com/qunit/qunit-git.js"
  description: "Javascript unit testing framework (JS)"
  version: "1.1.0pre"
  file_name: "qunit.js"

"qunit.css":
  url: "http://code.jquery.com/qunit/qunit-git.css"
  description: "Javascript unit testing framework (CSS)"
  version: "1.1.0pre"
  file_name: "qunit.css"

"jslitmus":
  url: "https://raw.github.com/broofa/jslitmus/master/jslitmus.js"
  description: "Simple, easy, javascript benchmark testing"
  version: "0.0.1"
  file_name: "jslitmus.js"
