underscore: 
  url: "https://github.com/documentcloud/underscore/raw/{version}/underscore.js"
  description: "javascript's utility belt"
  compressed: "underscore-min.js"
  version: "1.1.7"

raphael:
  url: "https://github.com/DmitryBaranovskiy/raphael/raw/v{version}/raphael.js"
  description: "raphael vector library"
  "compressed": "raphael-min.js"
  version: "1.4.7"

"g.raphael":
  url: "https://github.com/DmitryBaranovskiy/g.raphael/raw/v{version}/g.raphael.js"
  description: "charting for raphael"
  "compressed": "g.raphael-min.js"
  version: "0.4.1"
  dependencies:
    "raphael": "1.4.7"

"g.bar":
  url: "https://github.com/DmitryBaranovskiy/g.raphael/raw/v{version}/g.bar.js"
  description: "bar charting for raphael"
  "compressed": "g.bar-min.js"
  version: "0.4.1"
  dependencies:
    "g.raphael": "0.4.1"

"g.dot":
  url: "https://github.com/DmitryBaranovskiy/g.raphael/raw/v{version}/g.dot.js"
  description: "dot charting for raphael"
  "compressed": "g.dot-min.js"
  version: "0.4.1"
  dependencies:
    "g.raphael": "0.4.1"

"g.line":
  url: "https://github.com/DmitryBaranovskiy/g.raphael/raw/v{version}/g.line.js"
  description: "line charting for raphael"
  "compressed": "g.line-min.js"
  version: "0.4.1"
  dependencies:
    "g.raphael": "0.4.1"

"g.pie":
  url: "https://github.com/DmitryBaranovskiy/g.raphael/raw/v{version}/g.pie.js"
  description: "pie charting for raphael"
  "compressed": "g.pie-min.js"
  version: "0.4.1"
  dependencies:
    "g.raphael": "0.4.1"

"jquery":
  url: "http://code.jquery.com/jquery-{version}.js"
  description: "jquery core framework"
  "compressed": "jquery-{version}.min.js"
  "filename": "jquery.js"
  version: "1.6.2"

"jquery-mobile":
  url: "http://code.jquery.com/mobile/{version}/jquery.mobile-{version}.js"
  description: "touch-optimized web framework for smartphones & tablets"
  "filename": "jquery.mobile.js"
  version: "1.0a4"
  dependencies:
    "jquery": "1.5.1"

"processing.js":
  url: "http://processingjs.org/content/download/processing-js-{version}/processing-{version}.js"
  description: "a port of the Processing visualization language"
  "filename": "processing.js"
  version: "1.1.0"

"d3":
  url: "https://github.com/mbostock/d3/raw/v{version}/d3.js"
  description: "A JavaScript visualization library for HTML and SVG."
  "filename": "d3.js"
  version: "1.17.0"

"d3.behavior":
  url: "https://github.com/mbostock/d3/raw/v{version}/d3.behavior.js"
  description: "Event module for d3. A JavaScript visualization library for HTML and SVG."
  version: "1.11.0"
  dependencies:
    "d3": "1.17.0"

"d3.chart":
  url: "https://github.com/mbostock/d3/raw/v{version}/d3.chart.js"
  description: "Chart module for d3. A JavaScript visualization library for HTML and SVG."
  version: "1.11.0"
  dependencies:
    "d3": "1.17.0"

"d3.csv":
  url: "https://github.com/mbostock/d3/raw/v{version}/d3.csv.js"
  description: "CSV parser module for d3. A JavaScript visualization library for HTML and SVG."
  version: "1.11.0"
  dependencies:
    "d3": "1.17.0"

"d3.geo":
  url: "https://github.com/mbostock/d3/raw/v{version}/d3.geo.js"
  description: "Geo module for d3. A JavaScript visualization library for HTML and SVG."
  version: "1.11.0"
  dependencies:
    "d3": "1.17.0"

"d3.geom":
  url: "https://github.com/mbostock/d3/raw/v{version}/d3.geom.js"
  description: "Geometry module for d3. A JavaScript visualization library for HTML and SVG."
  version: "1.11.0"
  dependencies:
    "d3": "1.17.0"

"d3.layout":
  url: "https://github.com/mbostock/d3/raw/v{version}/d3.layout.js"
  description: "Layout module for d3. A JavaScript visualization library for HTML and SVG."
  version: "1.11.0"
  dependencies:
    "d3": "1.17.0"

"d3.time":
  url: "https://github.com/mbostock/d3/raw/v{version}/d3.time.js"
  description: "Time module for d3. A JavaScript visualization library for HTML and SVG."
  version: "1.11.0"
  dependencies:
    "d3": "1.17.0"

"date.js":
  url: "http://datejs.googlecode.com/files/date.js"
  description: "Datejs is an open source JavaScript Date library for parsing, formatting and processing."
  version: "1.0 Alpha-1"

"backbone":
  url: "https://github.com/documentcloud/backbone/raw/{version}/backbone.js"
  compressed: "backbone-min.js"
  description: "Backbone supplies structure to Javascript Apps by providing models, views, collections, and events"
  version: "0.5.1"

"zepto":
  url: "https://github.com/madrobby/zepto/raw/v{version}/src/zepto.js"
  description: "zepto.js is a minimalist inlinable framework for mobile WebKit browsers, with a jQuery-like chaining syntax"
  version: "0.5"

"iscroll":
  url: "https://github.com/cubiq/iscroll/raw/master/src/iscroll.js"
  description: "Hardware accelerated scroll for mobile webkit"
  version: "4.0"

"iscroll-lite":
  url: "https://github.com/cubiq/iscroll/raw/master/src/iscroll-lite.js"
  description: "Hardware accelerated scroll for mobile webkit"
  version: "4.0"

"modernizr":
  url: "https://github.com/Modernizr/Modernizr/raw/v{version}/modernizr.js"
  description: "Feature detection to test browsers against upcoming features"
  version: "1.7"

"mustache.js":
  url: "https://raw.github.com/janl/mustache.js/{version}/mustache.js"
  description: "Minimal templating with {{mustaches}} in JavaScript"
  version: "0.3.0"
